### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by devakumetsu** [Oleffa/LeagueAI#1]
how can I test this?  would like to test it and give you some feedback. seen like interesting project.

Regards.-

**Comment by Oleffa** [comment]
Hi, thanks for your interest in the project! 

1. You need tensorflow running on your machine (https://www.tensorflow.org/install/install_windows)
preferably with GPU. Also you need to install the tensor flow object-detection-api (https://github.com/tensorflow/models/tree/master/research/object_detection)
2. Furthermore you need a python environment. I used IPython with Jupyter (https://jupyter.org/) as development environment, but I uploaded the .py file of the code as well so you can download and run the code however you like.
3. Unpack the custom tensorflow model for detecting league of legends objects which i trained. 
EDIT: The model is now in the repository: https://github.com/Oleffa/LeagueAI/blob/master/LeagueAI_v3.zip
Outdated: I uploaded that to Google Drive (https://drive.google.com/open?id=1zuGJRwjNgHHEg43EX9VjNWYOM1pSlQY5) 72MB)
4. Copy the unpacked Folder in the models-master/research/object_detection folder

5. Now you should be able to run the python script (depending on your machine it might take a while to load the tensorflow model etc. -> Success if an output window shows up and shows the AI view) 

6. Currently it is configured to read all pixels from your primary screen and perform object detection + clicking actions on it. So it works best if you have the game run in fullscreen on your primary screen as usual and have the output window that will pop up on a second screen or in the background. Resolutions may be adjusted depending on your monitor resolution.

Hints: As soon as the object detection starts the program will execute clicks (so adding a delay before the main routine can give you some time to tab into the game. Pressing Q on your keyboard stops the main routine but you have to quickly tab out of the game and set focus to the output window).
A tutorial that gives a good instruction on how to set up tensorflow for object detection is this one: https://pythonprogramming.net/introduction-use-tensorflow-object-detection-api-tutorial/

Greetings

EDIT: added some more info to the installation instructions step 3

**Comment by Anishfish** [comment]
Hi Oleffa,
  I was wondering if you were continuing work on this project, and if so, I was wondering if I could get involved in any way. If not, I was thinking about trying to create a similar project and would be grateful for any advice concerning an AI for league of legends.

Thanks,
Anish Karthik

**Comment by Oleffa** [comment]
Hi Anish,

Right now I don't have much planned for the project. Just some ideas on what could be done next. If you want to you can of course create a branch of the project. If you need help on setting it up try using the guide i wrote in this issue and if you have questions just ask!

In general to get started with object detection I can recommend the tutorial by sentdex at: https://pythonprogramming.net/introduction-use-tensorflow-object-detection-api-tutorial/ It basically covers the setup of the object detection with tensorflow and how to use custom object detection models.

Best Regards,
Oliver
