### ISSUE TITLE
 training\LeagueAI_v2.pbtxt : The system cannot find the path specified.

### ISSUE THREAD

**Issue by hmai** [Oleffa/LeagueAI#6]
I spent a day getting everything set up. Now I'm blocked with this error message.

It seems like the github repo is missing the training data. Can you please provide it?

(FYI, the updated LeagueAI_v3.zip link expired so I'm not able to access it)

Thanks!

**Comment by Oleffa** [comment]
Hi,

this error occurs when there is no label map in the folder training/. The label map contains the translation from the id of the detected object to a natural language representation. For example, if the object detection network detects and object with ID 2, it would be an enemy minion.

I have added the label map to the repo in: https://github.com/Oleffa/LeagueAI/blob/master/LeagueAI_v3.pbtxt (I also renamed it to "LeagueAI_v3.pbtxt" and made the according changes in the jupyter notebook and the python file).

About the LeagueAI_v3.zip, I checked all links in the descriptions and the file is also in the repo. Could you maybe specify which link exactly does not work? https://github.com/Oleffa/LeagueAI/blob/master/LeagueAI_v3.zip

The LeagueAI_v3.zip contains the trained model and the checkpoints from the training.

If you have more questions just let me know!

Best Regards
